teachers = sorted(["Conrad",
                   "Brown",
                   "Camilo",
                   "Costagliola",
                   "Darlington",
                   "Norton",
                   "Rizzo",
                   "Rivera",
                   "Najarian",
                   "St. Laurent",
                   "Brennan",
                   "Messina",
                   "Stevens, Karen",
                   "Hall, Matthew",
                   "Prather",
                   "Martin, Bill",
                   "Chaff",
                   "Gibson, Joanne",
                   "Samia",
                   "Hawes",
                   "de Kelley",
                   "Abbott",
                   "Martin, Melissa",
                   "Bergey",
                   "Duncan",
                   "Dwyer",
                   "Fortier",
                   "Gould",
                   "Hutchins",
                   "Jones",
                   "Lenzi",
                   "Cataldo",
                   "Burm",
                   "Hinchcliff",
                   "Keeler",
                   "Palen",
                   "Pascucci",
                   "Pisano",
                   "Waterman",
                   "Znamierowski",
                   "Ganci",
                   "Aubrey",
                   "D'Alise",
                   "Emory",
                   "Giggie",
                   "Howland",
                   "Janeiro",
                   "Johnson",
                   "Keene",
                   "Meagher",
                   "Mitchell",
                   "Niles",
                   "Parsons",
                   "Pellerin",
                   "Percival",
                   "Rickley",
                   "Shea",
                   "Walke",
                   "Whalen",
                   "Delforge",
                   "Choquette",
                   "Consentino",
                   "Daviso",
                   "Desjardins",
                   "Frisk",
                   "Hofius",
                   "Meehan",
                   "Michaud, Meghan",
                   "Worthley",
                   "Roddy",
                   "Koutroubas",
                   "Gleason",
                   "Langevin",
                   "Breen",
                   "Desfosse",
                   "McVeigh",
                   "Salvesen",
                   "Crowley",
                   "Richard",
                   "Armstrong",
                   "Arnold",
                   "Ciampa",
                   "DiBenedetto",
                   "Namvar",
                   "Foley",
                   "Haltmaier",
                   "Hibino, Alan",
                   "Hibino, Krista",
                   "Ogrodowczyk",
                   "Ragucci",
                   "Rainha",
                   "Reidy",
                   "Waters",
                   "Weldin",
                   "Willis",
                   "Mulert",
                   "Howell",
                   "Berube",
                   "Powers, Deb",
                   "Ruseckas",
                   "Emery",
                   "Fazio",
                   "Martini",
                   "McManus",
                   "Puglisi",
                   "Salois",
                   "Murnane",
                   "McNally",
                   "Bourgeios",
                   "Houston",
                   "Jamgochian",
                   "Martin, John",
                   "Peters",
                   "Reide",
                   "Vargas",
                   "White",
                   "Russell",
                   "Dubois",
                   "Sanborn",
                   "Bledsoe",
                   "Caveney",
                   "Cutler",
                   "Donovan",
                   "Doucet",
                   "Fisher",
                   "Givens",
                   "Gupte",
                   "Holm-Andersen",
                   "Iannuccilli",
                   "Jannetti",
                   "Kalf",
                   "L'Ecuyer",
                   "Marx",
                   "Rodier",
                   "Valenti",
                   "Wall",
                   "Bock",
                   "Bach",
                   "Chachus",
                   "Gibson, Brendan",
                   "Hopkins",
                   "Masters",
                   "McCarthy",
                   "Michaud, Rob",
                   "Pina",
                   "Rand",
                   "Ream",
                   "Robb",
                   "Vives",
                   "Wagner",
                   "Avcioglu",
                   "Perry",
                   "Yarid",
                   "Grange",
                   "Kirby",
                   "Levin",
                   "DeGenova",
                   "Tarricone",
                   "Bailey",
                   "Bernie",
                   "Blank",
                   "O Donnell",
                   "Bonin",
                   "Burke",
                   "Burns",
                   "Caron, Alison",
                   "Caron, Evelyn",
                   "Cesar",
                   "Collins, Jennifer",
                   "Collins, Lisa",
                   "Costello, Jim",
                   "Cross",
                   "Croswell",
                   "Cummings",
                   "Damphousse",
                   "Davis",
                   "Davidson",
                   "Day",
                   "Drueke",
                   "Farra",
                   "Fitzgerald",
                   "Ganley",
                   "Germaine",
                   "Gillespie",
                   "Griffin",
                   "Hamilton",
                   "Hand",
                   "Hecht",
                   "Kapamajian",
                   "Kropiwnicki",
                   "Lawrence",
                   "Lemieux",
                   "Mandelbaum",
                   "Maniachi",
                   "Meltsakos",
                   "Mugford",
                   "Papadopoulos",
                   "Paris",
                   "Rowe",
                   "Saad",
                   "Scoggins",
                   "Scott",
                   "Serapiglia",
                   "Sheehy",
                   "Spinale",
                   "Stevens, Lincoln",
                   "Thiede",
                   "Timpko",
                   "Torrisi-Neel",
                   "Tremblay",
                   "Tweedale",
                   "Vazquez",
                   "Westmacott",
                   "Woods",
                   "Yanofsky",
                   "Young",
                   "Kuhlmann",
                   "Coufus",
                   "Schofield",
                   "Hoar",
                   "Nice",
                   "Wilson",
                   "Butkowich",
                   "Trant",
                   "Maglione",
                   "Bouchard",
                   "Bergner",
                   "Peterson",
                   "Gardner",
                   "Costello, Kerry",
                   "Allen",
                   "Couture",
                   "Deschenes",
                   "Francis",
                   "Gaudiano",
                   "Gonzalez",
                   "Hall, Peter",
                   "Jordan",
                   "Kostousova",
                   "Perez-Lucafo",
                   "Powers, Tom",
                   "Rodriguez",
                   "Shaknovsky",
                   "Wu",
                   "Zawil",
                   "Campbell",
                   "Remy",
                   "Song",
                   "Howansky",
                   "Deshler",
                   "Kinsman",
                   "Reusch"
                   ])
